Repository astrogilda/tsbootstrap, pull requests merged in 2024-04, with the labels that each got.

#115 Update pyproject.toml and bypass hypothesis healthchecks
  .github/workflows/sync_requirements.yml
  .gitignore
  pyproject.toml
  tests/test_time_series_simulator.py
Labels: enhancement

#120 [Automated] Update documentation requirements
  docs/requirements.txt
Labels: automated PR

#123 linked to buymeacoffee
  .github/FUNDING.yml
Labels: enhancement

#130 added uv as an installation option
  .gitignore
  README.md
  pyproject.toml
  uv_vs_pip.jpg
Labels: enhancement, good first issue

#132 added doc_improvement and config.yml in issues workflow
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/doc_improvement.md
Labels: enhancement

#117 Replace prints with logging
  src/tsbootstrap/block_generator.py
  src/tsbootstrap/block_resampler.py
  src/tsbootstrap/markov_sampler.py
  src/tsbootstrap/ranklags.py
  tests/test_base_bootstrap_configs.py
  tests/test_block_bootstrap.py
  tests/test_block_generator.py
  tests/test_block_resampler.py
  tests/test_time_series_model.py
  tests/test_time_series_simulator.py
  tests/test_tsfit.py
Labels: bug

#74 [DOC] remove public docs on configs
  docs/source/base_bootstrap_configs.rst
  docs/source/block_bootstrap_configs.rst
  docs/source/index.rst
Labels: documentation

#135 [ENH] boilerplate layer, streamlied extension contract
  src/tsbootstrap/base_bootstrap.py
  src/tsbootstrap/block_bootstrap.py
Labels: enhancement

#138 137 update docstrings, typehints, ci.yml and precommit package versions
  .github/workflows/CI.yml
  .pre-commit-config.yaml
  pyproject.toml
  src/tsbootstrap/base_bootstrap.py
  src/tsbootstrap/base_bootstrap_configs.py
  src/tsbootstrap/block_bootstrap.py
  src/tsbootstrap/block_bootstrap_configs.py
  src/tsbootstrap/block_generator.py
  src/tsbootstrap/block_length_sampler.py
  src/tsbootstrap/block_resampler.py
  src/tsbootstrap/bootstrap.py
  src/tsbootstrap/markov_sampler.py
  src/tsbootstrap/ranklags.py
  src/tsbootstrap/registry/tests/test_tags.py
  src/tsbootstrap/time_series_model.py
  src/tsbootstrap/time_series_simulator.py
  src/tsbootstrap/utils/odds_and_ends.py
  src/tsbootstrap/utils/types.py
  src/tsbootstrap/utils/validate.py
  tests/test_block_generator.py
  tests/test_block_resampler.py
  tests/test_time_series_simulator.py
Labels: bug, documentation, enhancement, good first issue, dependencies

#140 moved n_bootstraps to first position in all classes in bootstrap.py
  src/tsbootstrap/bootstrap.py
Labels: enhancement, good first issue

#136 [ENH] test for init signature conventions, simplified `get_n_bootstraps`
  src/tsbootstrap/base_bootstrap.py
  src/tsbootstrap/tests/test_all_bootstraps.py
Labels: enhancement

#127 [ENH] extension template for bootstrap algorithms
  extension_templates/bootstrap.py
Labels: documentation

#134 added use of uv instead of pip in CI.yml
  .github/workflows/CI.yml
  docs/source/conf.py
Labels: enhancement, maintenance

#143 142 miscellaneous maintenance
  .github/workflows/CI.yml
  .github/workflows/release.yml
  .pre-commit-config.yaml
  docs/source/conf.py
  extension_templates/bootstrap.py
  pyproject.toml
  src/tsbootstrap/base_bootstrap.py
  src/tsbootstrap/bootstrap.py
  src/tsbootstrap/tests/test_all_bootstraps.py
Labels: bug, good first issue

#141 [DOC] improved README structure to improve user journey
  README.md
Labels: documentation

#145 Update README.md
  README.md
Labels: documentation, good first issue

#146 changed macos-latest to macos-13
  .github/workflows/CI.yml
  .github/workflows/release.yml
Labels: maintenance

#126 125 update roadmap
  README.md
Labels: documentation, good first issue
