Repository astrogilda/tsbootstrap, pull requests merged in 2024-02, with the labels that each got.

#39 feat: isolate `arch` and `statsmodels` as soft dependencies, new `all_extras` soft dependency set
  .github/workflows/CI.yml
  pyproject.toml
  src/tsbootstrap/ranklags.py
  src/tsbootstrap/time_series_model.py
  src/tsbootstrap/time_series_simulator.py
  src/tsbootstrap/tsfit.py
  src/tsbootstrap/utils/types.py
  src/tsbootstrap/utils/validate.py
  tests/_nopytest_tests.py
  tests/test_bootstrap.py
  tests/test_time_series_model.py
  tests/test_tsfit.py
Labels: dependencies

#52 feat: isolate `scikit-learn-extra`
  pyproject.toml
  src/tsbootstrap/markov_sampler.py
Labels: dependencies

#53 maint: move `furo` to doc dependences
  pyproject.toml
Labels: dependencies

#54 maint: finish consolidation of dependencies
  .github/workflows/CI.yml
  pyproject.toml
  src/tsbootstrap/markov_sampler.py
  tests/test_bootstrap.py
  tests/test_markov_sampler.py
  tests/test_ranklags.py
  tests/test_time_series_simulator.py
Labels: dependencies

#57 maint: base `pyproject` and CI on `pip` (from `poetry`), windows and 3.12 tests
  .github/workflows/CI.yml
  pyproject.toml
Labels: dependencies

#60 maint: python 3.8 and 3.9 support - based on `pip` `pyproject.toml`
  .github/workflows/CI.yml
  pyproject.toml
  src/tsbootstrap/base_bootstrap.py
  src/tsbootstrap/base_bootstrap_configs.py
  src/tsbootstrap/block_bootstrap.py
  src/tsbootstrap/block_bootstrap_configs.py
  src/tsbootstrap/block_generator.py
  src/tsbootstrap/block_length_sampler.py
  src/tsbootstrap/block_resampler.py
  src/tsbootstrap/bootstrap.py
  src/tsbootstrap/markov_sampler.py
  src/tsbootstrap/ranklags.py
  src/tsbootstrap/time_series_model.py
  src/tsbootstrap/time_series_simulator.py
  src/tsbootstrap/tsfit.py
  src/tsbootstrap/utils/odds_and_ends.py
  src/tsbootstrap/utils/types.py
  src/tsbootstrap/utils/validate.py
  tests/test_base_bootstrap_configs.py
  tests/test_block_bootstrap.py
  tests/test_block_resampler.py
  tests/test_bootstrap.py
  tests/test_markov_sampler.py
  tests/test_validate.py
Labels: dependencies

#61 doc: remove superfluous `pandas` import from `README.md` example
  README.md
Labels: documentation

#66 feat: 44 sklearn compatible interface (with fkiraly)
  .github/workflows/CI.yml
  src/tsbootstrap/base_bootstrap.py
  src/tsbootstrap/base_bootstrap_configs.py
  src/tsbootstrap/block_bootstrap.py
  src/tsbootstrap/block_bootstrap_configs.py
  src/tsbootstrap/bootstrap.py
  tests/test_block_bootstrap.py
  tests/test_block_bootstrap_configs.py
  tests/test_bootstrap.py
Labels: enhancement

#26 feat: `scikit-base` registry and testing framework
  .github/workflows/CI.yml
  src/tsbootstrap/base_bootstrap.py
  src/tsbootstrap/base_bootstrap_configs.py
  src/tsbootstrap/block_bootstrap.py
  src/tsbootstrap/block_bootstrap_configs.py
  src/tsbootstrap/block_length_sampler.py
  src/tsbootstrap/bootstrap.py
  src/tsbootstrap/registry/__init__.py
  src/tsbootstrap/registry/_lookup.py
  src/tsbootstrap/registry/_tags.py
  src/tsbootstrap/registry/tests/__init__.py
  src/tsbootstrap/registry/tests/test_tags.py
  src/tsbootstrap/tests/__init__.py
  src/tsbootstrap/tests/scenarios/__init__.py
  src/tsbootstrap/tests/scenarios/scenarios.py
  src/tsbootstrap/tests/scenarios/scenarios_bootstrap.py
  src/tsbootstrap/tests/scenarios/scenarios_getter.py
  src/tsbootstrap/tests/test_all_bootstraps.py
  src/tsbootstrap/tests/test_all_estimators.py
  src/tsbootstrap/tests/test_class_register.py
  src/tsbootstrap/tests/test_switch.py
  src/tsbootstrap/utils/__init__.py
  src/tsbootstrap/utils/dependencies.py
  src/tsbootstrap/utils/estimator_checks.py
  tests/test_base_bootstrap_configs.py
  tests/test_block_bootstrap.py
  tests/test_bootstrap.py
Labels: enhancement
