Repository astrogilda/tsbootstrap, pull requests merged in 2024-03, with the labels that each got.

#84 feat: ensure bootstrap tests also run via `check_estimator`
  src/tsbootstrap/tests/test_class_register.py
Labels: enhancement

#89 bounded hmmlearn to 0.3.1(inclusive)
  pyproject.toml
Labels: bug

#86 changed test_ratio from 0.2 to 0 by default
  src/tsbootstrap/base_bootstrap.py
Labels: bug

#91 added bumpversion to gitignore and created CI for docs/requirements.txt
  .github/scripts/update_requirements.py
  .github/workflows/sync_requirements.yml
  .gitignore
  pyproject.toml
Labels: bug

#92 Stop tracking bumpversion files
  .bumpversion.cfg
  .github/workflows/bumpversion.yml
Labels: enhancement

#94 90 update docsrequirementstxt automatically based on pyprojecttoml
  .github/scripts/update_requirements.py
  docs/requirements.txt
Labels: bug

#96 added all contributors bot
  .all-contributorsrc
  README.md
Labels: enhancement

#100 Delete .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: bug, documentation

#101 feat: removes stray todo comments from `base_bootstrap`
  src/tsbootstrap/base_bootstrap.py
Labels: enhancement

#83 feat: extend suite test coverage to further `bootstrap` contract elements - equal shape as origial series, `test_ratio`, number of bootstraps
  src/tsbootstrap/tests/test_all_bootstraps.py
Labels: enhancement

#103 82 stationary bootstrap fails tests sporadically
  src/tsbootstrap/block_generator.py
  src/tsbootstrap/block_length_sampler.py
  src/tsbootstrap/tests/test_all_bootstraps.py
  src/tsbootstrap/tests/test_all_estimators.py
  src/tsbootstrap/tests/test_class_register.py
  src/tsbootstrap/utils/estimator_checks.py
  tests/test_block_bootstrap.py
  tests/test_block_generator.py
Labels: bug

#111 added 6 skipif statements
  CITATION.cff
  docs/source/conf.py
  pyproject.toml
  tests/test_bootstrap.py
Labels: bug

#112 bug: fix release action
  .github/workflows/release.yml
Labels: bug
