Repository astrogilda/tsbootstrap, pull requests merged in 2024-05, with the labels that each got.

#150 added mp.pool in _generate_samples
  src/tsbootstrap/base_bootstrap.py
  src/tsbootstrap/block_bootstrap.py
  src/tsbootstrap/tests/test_all_bootstraps.py
  src/tsbootstrap/tsfit.py
Labels: enhancement, good first issue

#148 [DOC] improved formatting of README roadmap
  README.md
Labels: documentation

#152 uncommented several codecov steps in ci
  .github/workflows/CI.yml
  commitlint.config.js
  tests/test_time_series_simulator.py
Labels: bug

#155 passed n_bootstraps as param to blockconfig classes
  src/tsbootstrap/block_bootstrap.py
Labels: bug
